<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Invoices' => '@@الفواتير@@',
    'Items' => '@@الأصناف@@',
    'AVG Cost' => 'متوسط التكلفة',
    'Active Rate' => 'أعلى تعرفة',
    'Add Category' => 'اضافة نوع',
    'Add New Category' => 'أضف نوع جديد',
    'Add New Inventory' => 'اضافة مخزن جديد',
    'Add New Item' => 'اضافة صنف جديد',
    'Add New Stock' => 'تخزين',
    'Add This Inventory' => 'اضافة الى مخزن',
    'Add this Item' => 'اضف الصنف',
    'Add to Stock' => 'اضف المخزون',
    'Address' => 'العنوان',
    'Alias' => 'اختصار',
    'Available' => 'متوفر',
    'Buying Price' => 'سعر الشراء',
    'Category' => 'النوع',
    'Category Name' => 'اسم النوع',
    'Cost of Goods' => 'تكلفة المنتجات',
    'Created AT' => 'بتاريخ',
    'Gross Sale' => 'اجمالي البيع',
    'Highest Rate' => 'أعلى تعرفه',
    'ID' => 'رقم',
    'Inventories' => 'المخازن',
    'Inventory' => 'المخزن',
    'Inventory Name' => 'اسم المخزن',
    'Item' => 'صنف',
    'Item Description' => 'وصف الصنف',
    'Item Name' => 'اسم الصنف',
    'Item No' => 'رقم الصنف',
    'Items Count' => 'عدد الصنف',
    'Magin ratio' => 'نسبة الهامش',
    'Margin Profit' => 'هامش الربح',
    'Margin Ratio' => 'هامش الزيادة',
    'Name' => 'اسم',
    'No Reference' => 'ﻻ توجد اشارة',
    'Phone No' => 'رقم التلفون',
    'Product' => 'صنف',
    'Quantity' => 'الكمية',
    'Reference' => 'اشارة',
    'Returned' => 'راجع',
    'Select An Inventory ' => 'اختار المخزن',
    'Select Color' => 'اختار لون',
    'Selling Price' => 'سعر البيع',
    'Short Name' => 'اختصار',
    'Sold' => 'مباع',
    'Sold OUT' => 'مباع',
    'Stock Value' => 'قيمة المخزون',
    'Stocked IN' => 'مخزون',
    'Total' => 'الجملة',
    'Total Returned Value' => 'اجمالي الراجع',
    'Total Sold Value' => 'اجمالي المباع',
    'Total Stock Value' => 'اجمالي المخزون',
    'Total Transfered Value' => 'اجمالي المحول',
    'Transfere' => 'تحويل',
    'Transfered' => 'محول',
    'Type Item Name ' => 'اكتب اسم الصنف',
    'USD' => 'دوﻻر',
    'Update This Inventory' => 'تعديل المخزن',
    'account_group' => 'مجموعة الحساب',
    'asset_account_id' => 'حساب ال ',
    'color_class' => 'اللون',
    'created_at' => 'زمن الاضافة',
    'created_by' => 'اضيف بواسطة',
    'from' => 'من مخزن',
    'item' => 'الصنف',
    'minimum' => 'أقل',
    'quantity' => 'الكمية',
    'to' => 'الى مخزن',
    'total category items : ' => 'عدد الأصناف في النوع ',
    'total inventory items : ' => 'جملة الأصناف في المخزن',
    'update' => 'تعديل',
    'updated_at' => 'عدل بتاريخ',
    'updated_by' => 'عدل بواسطة',
    'Update Price' => 'تعديل السعر',
];
