<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '' => '',
    'amountDue' => '',
    'inventory total :' => '@@اجمالي المخن@@',
    '#NO' => '#رقم',
    'AMOUNT DUE' => 'المبلغ المتبقي',
    'Amount' => 'المبلغ',
    'Available' => 'المتوفر',
    'Bank Name' => 'اسم البنك',
    'Cash' => 'كاش',
    'Cheque' => 'شيك',
    'Cheque Date' => 'تاريخ الشيك',
    'Cheque No' => 'رقم الشيك',
    'Cient' => 'عميل',
    'Client' => 'العميل',
    'Cost' => 'تكلفة',
    'Create' => 'انشاء',
    'Create Invoices' => 'انشاء فاتورة',
    'Date' => 'تاريخ',
    'Discount' => 'تخفيض',
    'Due Date' => 'تاريخ التسليم',
    'Gross Sale' => 'اجمالي المبيعات',
    'Inventory' => 'المخزن',
    'Invoice' => 'فاتورة',
    'Invoices' => 'فواتير',
    'Item' => 'صنف',
    'LineTotal' => 'اجمالي',
    'Mode' => 'طريقة',
    'PAID' => 'مدفوع',
    'Paid At' => 'دفع بتاريخ',
    'Pay' => 'ادفع',
    'Price' => 'سعر',
    'Print' => 'طباعة',
    'Promise' => 'وعد',
    'Quantity' => 'كمية',
    'Return' => 'استرجاع',
    'SUBTOTAL' => 'جملة',
    'Save' => 'حفظ',
    'Status' => 'حاله',
    'TAX' => 'ضرائب',
    'TOTAL' => 'اجمالي',
    'Total' => 'الاجمالي',
    'Type' => 'نوع',
    'View' => 'انتقال',
    'Total Paid' => 'اجمالي المدفوع',
    'Remaining' => 'المتبقي',
];
